apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Example Application 1
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: app1
    repoURL: git@github.com:utpk/openshift-gitops-example-app.git
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated: {}
