kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: git-managed-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: myuser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
